#!/bin/sh
# Build a PATH shim that satisfies cores wanting a bare `python`.
#
#     eval "$(tools/python-shim.sh)"     # adds the shim to PATH for this shell
#     tools/python-shim.sh --path        # just print the directory
#
# The Seeed nRF52 platform's packaging recipe shells out to `python`, which
# modern macOS does not ship. The compile succeeds, produces the .hex, and then
# the UPLOAD fails hunting a .zip that was never built -- a failure whose
# message names only the missing file, not the missing interpreter.
#
# This script exists because the obvious fixes are both wrong, and one of them
# did real damage here on 2026-09-03:
#
#   A SYMLINK DOES NOT WORK. /usr/bin/python3 is the Command Line Tools stub
#   and dispatches on argv[0]; invoked as `python` it hunts for a developer
#   tool of that name and dies with "xcode-select: Failed to locate 'python'",
#   which surfaces as arduino-cli exit status 72 long after a clean compile.
#
#   THE TARGET MUST BE ABSOLUTE. A wrapper containing `exec python3 "$@"`
#   re-resolves through PATH, finds itself, and execs itself forever. That
#   exact line was written into Homebrew's Cellar here, overwrote the real
#   python3.13 binary with 28 bytes, and broke every ESP32 build -- they shell
#   out to python for partition tables -- for sixteen hours. One sketch sat in
#   a hung compile the whole time.
#
# So: a script, not a symlink; an absolute target; and inside the repository,
# never in the Homebrew prefix and never in /tmp.
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
SHIM="$ROOT/.git/shim"
PY=/usr/bin/python3

[ -x "$PY" ] || { echo "no $PY on this machine" >&2; exit 1; }

mkdir -p "$SHIM"
cat > "$SHIM/python" <<EOF
#!/bin/sh
# Generated by tools/python-shim.sh -- absolute target on purpose; see there.
exec $PY "\$@"
EOF
chmod +x "$SHIM/python"
ln -sf "$PY" "$SHIM/python3"

# Prove it before claiming it: invoked as `python`, through the shim.
got=$(PATH="$SHIM:$PATH" python -c 'import sys; print(sys.version.split()[0])' 2>&1) || {
  echo "shim built but does not run: $got" >&2; exit 1; }

if [ "${1:-}" = "--path" ]; then
  echo "$SHIM"
else
  echo "# python $got via $SHIM"
  echo "export PATH=\"$SHIM:\$PATH\""
fi
